<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>GUI_QLResort</RootNamespace>
    <AssemblyName>GUI_QLResort</AssemblyName>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Transactions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BUS_QLResort\BUS_QLResort.csproj" />
    <ProjectReference Include="..\ET_QLResort\ET_QLResort.csproj" />
    <ProjectReference Include="..\Tool_QLResort\Tool_QLResort.csproj" />
    <ProjectReference Include="..\DAL_QLResort\DAL_QLResort.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>
</Project>
