<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>GUI_QLResort</RootNamespace>
    <AssemblyName>GUI_QLResort</AssemblyName>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <ReferencePath>C:\Program Files (x86)\SAP BusinessObjects\Crystal Reports for .NET Framework 4.0\Common\SAP BusinessObjects Enterprise XI 4.0\win64_x64\dotnet\</ReferencePath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Transactions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BUS_QLResort\BUS_QLResort.csproj" />
    <ProjectReference Include="..\ET_QLResort\ET_QLResort.csproj" />
    <ProjectReference Include="..\Tool_QLResort\Tool_QLResort.csproj" />
    <ProjectReference Include="..\DAL_QLResort\DAL_QLResort.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data" />
    <Reference Include="System.Web.Services">
      <HintPath>..\..\..\..\..\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="CrystalDecisions.CrystalReports.Engine, Version=13.0.4000.0, Culture=neutral, PublicKeyToken=692fbea5521e1304, processorArchitecture=MSIL">
      <HintPath>..\demo_p\bin\Debug\CrystalDecisions.CrystalReports.Engine.dll</HintPath>
    </Reference>
    <Reference Include="CrystalDecisions.ReportSource, Version=13.0.4000.0, Culture=neutral, PublicKeyToken=692fbea5521e1304, processorArchitecture=MSIL">
      <HintPath>..\demo_p\bin\Debug\CrystalDecisions.ReportSource.dll</HintPath>
    </Reference>
    <Reference Include="CrystalDecisions.Shared, Version=13.0.4000.0, Culture=neutral, PublicKeyToken=692fbea5521e1304, processorArchitecture=MSIL">
      <HintPath>..\demo_p\bin\Debug\CrystalDecisions.Shared.dll</HintPath>
    </Reference>
    <Reference Include="CrystalDecisions.Windows.Forms, Version=13.0.4000.0, Culture=neutral, PublicKeyToken=692fbea5521e1304, processorArchitecture=MSIL">
      <HintPath>..\demo_p\bin\Debug\CrystalDecisions.Windows.Forms.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="BaoCao.cs">
      <SubType>Component</SubType>
      <DependentUpon>BaoCao.rpt</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="BaoCaoTongQuat.cs">
      <SubType>Component</SubType>
      <DependentUpon>BaoCaoTongQuat.rpt</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Report\RP_TTKH.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>rp_TTKH.rpt</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Content Include="BaoCao.rpt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>CrystalDecisions.VSDesigner.CodeGen.ReportCodeGenerator</Generator>
      <LastGenOutput>BaoCao.cs</LastGenOutput>
    </Content>
    <Content Include="BaoCaoTongQuat.rpt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>CrystalDecisions.VSDesigner.CodeGen.ReportCodeGenerator</Generator>
      <LastGenOutput>BaoCaoTongQuat.cs</LastGenOutput>
    </Content>

    <EmbeddedResource Include="Report\rp_TTKH.rpt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>CrystalDecisions.VSDesigner.CodeGen.ReportCodeGenerator</Generator>
      <LastGenOutput>rp_TTKH.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="Report\rp_TTNV.rpt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>CrystalDecisions.VSDesigner.CodeGen.ReportCodeGenerator</Generator>
      <LastGenOutput>rp_TTNV.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{c0c07587-41a7-46c8-8fbd-3f9c8ebe2ddc}" />
  </ItemGroup>
</Project>
