<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BUS_QLResort\BUS_QLResort.csproj" />
    <ProjectReference Include="..\ET_QLResort\ET_QLResort.csproj" />
    <ProjectReference Include="..\Tool_QLResort\Tool_QLResort.csproj" />
    <ProjectReference Include="..\DAL_QLResort\DAL_QLResort.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>
